language: python
sudo: false
python:
  - "3.8"

install:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#travis-ci
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip3 install bikeshed

script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "c80b4dc18b55"
  - COMMIT_AUTHOR_EMAIL: "yoav@yoav.ws"
